get_filename_component(CURRENT_INSTALLED_DIR "../../" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_LIST_DIR}")
message(STATUS "Finding VCPKG x264 in ${CURRENT_INSTALLED_DIR}")


    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        set(X264_ROOT "${CURRENT_INSTALLED_DIR}/debug")
    else()
        set(X264_ROOT "${CURRENT_INSTALLED_DIR}")
    endif()
    # add_library(x264 SHARED IMPORTED)

    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        set(X264_STATIC_ROOT "${CURRENT_INSTALLED_DIR}/debug/static")
    else()
        set(X264_STATIC_ROOT "${CURRENT_INSTALLED_DIR}/static")
    endif()
    # add_library(x264 STATIC IMPORTED)


set(X264_INCLUDE_DIR "${CURRENT_INSTALLED_DIR}/include")
set(X264_INCLUDE_DIRS "${X264_INCLUDE_DIR}")
set(X264_LIBRARY "${X264_ROOT}/lib/libx264.lib")
set(X264_LIBRARIES ${X264_LIBRARY})

set(X264_STATIC_INCLUDE_DIR "${X264_STATIC_ROOT}/include")
set(X264_STATIC_INCLUDE_DIRS "${X264_STATIC_INCLUDE_DIR}" "X264_INCLUDE_DIR")
set(X264_STATIC_LIBRARY "${X264_STATIC_ROOT}/lib/libx264.lib")
set(X264_STATIC_LIBRARIES ${X264_LIBRARY})

# set_target_properties(x264 PROPERTIES
#   IMPORTED_LOCATION "${X264_LIBRARY}"
#   INTERFACE_INCLUDE_DIRECTORIES "${X264_INCLUDE_DIR}"
# )

find_package_handle_standard_args(X264 DEFAULT_MSG X264_LIBRARY X264_INCLUDE_DIR)